version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - app-databases:/mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
  
  web:
    build : .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  
  # mysqldb:
  #   image: mysql:5.7
  #   container_name: mysqldocker
  #   environment:
  #     MYSQL_ROOT_PASSWORD: $DB_PASSWORD
  #     MYSQL_DATABASE: $DB_NAME
  #   ports:
  #     - "${MYSQLDB_DOCKER_PORT}:${MYSQLDB_LOCAL_PORT}"
  #   volumes:
  #     - app-databases:/mysql 

volumes: 
  app-data:
  app-databases:
  
